spring:
  application:
    name: AspyPortfoliogenerator
  # Configuración de la base de datos H2
  datasource:
    url: jdbc:h2:mem:aspydb
    driver-class-name: org.h2.Driver
    username: aspy
    password:
  jpa:
    hibernate:
      ddl-auto: update
  # Habilitar la consola y la ruta url
  h2:
    console:
      enabled: true
      path: /h2-console